### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_components.neato.xxx'; 'custom_components.neato' is not a package

### ISSUE THREAD

**Issue by steeriks** [dshokouhi/hass-neato-custom-component#5]
Hi,

After upgrade to hass 0.88 this warnig/error occours!

Error loading custom_components.neato.**switch**. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.neato.switch'; 'custom_components.neato' is not a package

Error loading custom_components.neato.**vacuum**. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.neato.vacuum'; 'custom_components.neato' is not a package
Connection lost. Reconnecting…

Error loading custom_components.neato.**camera**. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.neato.camera'; 'custom_components.neato' is not a package

**Comment by dshokouhi** [comment]
Hello this custom component now needs an update to be in line with the new folder structure introduced in 0.88.  There is also a PR submitted to Home Assistant that will hopefully be in 0.89 which will replace this custom component as it is a better implementation.  I suggest you try out the code in this PR: https://github.com/home-assistant/home-assistant/pull/20779

**Comment by dshokouhi** [comment]
This is now fixed in the latest master branch and the feature is live in HA 0.89

**Comment by steeriks** [comment]
Hi,
Still get some confusing errors in 0.89

`Log Details (ERROR)
Fri Mar 08 2019 10:00:05 GMT+0100 (Central European Standard Time)
neato: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neato/vacuum.py", line 190, in update
    robot_map_id = self._robot_maps[self._robot_serial][0]['id']
IndexError: list index out of range`

**Comment by dshokouhi** [comment]
@steeriks do you have any persistent maps setup?

**Comment by steeriks** [comment]
Nope, No persistent maps.

**Comment by dshokouhi** [comment]
ok I think I have a fix for this, can you update your files to this branch and let me know if it works for you.  I am now checking to see if there are no maps along with multiple maps.  This should solve it.

https://github.com/dshokouhi/hass-neato-custom-component/tree/multiple_floorplans

**Comment by steeriks** [comment]
Perfect 👌

It looks good! Thanks 😊

**Comment by dshokouhi** [comment]
thank you for confirming :) once I get some users to confirm that map cleaning works for them I will go ahead and get this submitted.
